/**
 * Generates .opencode/plugins/dev-enforcer.ts.
 *
 * OpenCode subscribes to `tool.execute.before` events. The plugin enforces
 * the same rules as the Claude/Codex hooks by invoking the shared TS
 * dispatcher (`oisin-dev hook <name>`).
 */

import type { DevConfig } from '../config.js'

export function generateOpencodePlugin(_config: DevConfig): string {
  return `// dev-enforcer.ts — generated by @oisincoveney/dev
// Intercepts opencode tool.execute.before events and enforces the same rules
// as the Claude Code hooks via the shared TS dispatcher.

import { spawnSync } from 'node:child_process'

interface ToolEvent {
  tool: string
  input: Record<string, unknown>
}

function runHook(name: string, input: unknown): { allowed: boolean; message?: string } {
  const result = spawnSync('oisin-dev', ['hook', name], {
    input: JSON.stringify(input),
    encoding: 'utf8',
    timeout: 30_000,
  })

  if (result.status === 2) {
    return { allowed: false, message: result.stderr || 'Blocked by hook' }
  }
  return { allowed: true }
}

export default {
  name: 'dev-enforcer',
  async 'tool.execute.before'(event: ToolEvent): Promise<void> {
    const toolInput = { tool_input: event.input }

    if (event.tool === 'bash') {
      const destructive = runHook('destructive-command-guard', toolInput)
      if (!destructive.allowed) throw new Error(destructive.message)
      const coauthor = runHook('block-coauthor', toolInput)
      if (!coauthor.allowed) throw new Error(coauthor.message)
      return
    }

    if (['write', 'edit', 'multiedit', 'patch'].includes(event.tool)) {
      const imports = runHook('import-validator', toolInput)
      if (!imports.allowed) throw new Error(imports.message)
      const antipattern = runHook('ai-antipattern-guard', toolInput)
      if (!antipattern.allowed) throw new Error(antipattern.message)
      const style = runHook('ts-style-guard', toolInput)
      if (!style.allowed) throw new Error(style.message)
      return
    }

    if (event.tool === 'todowrite' || event.tool === 'todo_write') {
      const block = runHook('block-todowrite', toolInput)
      if (!block.allowed) throw new Error(block.message)
    }
  },
}
`
}
