/**
 * Generates .opencode/plugins/dev-enforcer.ts.
 *
 * OpenCode subscribes to `tool.execute.before` events. The plugin enforces
 * the same rules as the Claude/Codex hooks — destructive commands, fabricated
 * imports, TodoWrite→beads — by shelling out to the shared bash scripts.
 */

import type { DevConfig } from '../config.js'

export function generateOpencodePlugin(config: DevConfig): string {
  const hasTypescript = (config.languages ?? [config.language]).includes('typescript')
  const beadsEnabled = config.tools.includes('beads')

  return `// dev-enforcer.ts — generated by @oisincoveney/dev
// Intercepts opencode tool.execute.before events and enforces the same rules
// as the Claude Code hooks by running the shared bash hooks.

import { spawnSync } from 'node:child_process'
import { existsSync } from 'node:fs'
import { join } from 'node:path'

interface ToolEvent {
  tool: string
  input: Record<string, unknown>
}

const HOOKS_DIR = '.claude/hooks'
const HAS_TYPESCRIPT = ${JSON.stringify(hasTypescript)}
const BEADS_ENABLED = ${JSON.stringify(beadsEnabled)}

function toolKey(tool: string): string {
  return tool.toLowerCase().replace(/[^a-z0-9_]+/g, '_').replace(/^_+|_+$/g, '')
}

function isReadTool(key: string): boolean {
  return ['read', 'glob', 'grep'].some((name) => key === name || key.endsWith(\`_\${name}\`))
}

function isWriteTool(key: string): boolean {
  return ['write', 'edit', 'multiedit', 'multi_edit', 'patch', 'apply_patch'].some(
    (name) => key === name || key.endsWith(\`_\${name}\`),
  )
}

function isShellTool(key: string): boolean {
  return ['bash', 'shell', 'exec', 'exec_command'].some(
    (name) => key === name || key.endsWith(\`_\${name}\`),
  )
}

function isTodoTool(key: string): boolean {
  return ['todowrite', 'todo_write', 'todo'].some(
    (name) => key === name || key.endsWith(\`_\${name}\`),
  )
}

function runHook(name: string, input: unknown): { allowed: boolean; message?: string } {
  const path = join(HOOKS_DIR, name)
  if (!existsSync(path)) return { allowed: true }

  const result = spawnSync(path, [], {
    input: JSON.stringify(input),
    encoding: 'utf8',
    timeout: 30_000,
  })

  if (result.status === 2) {
    return { allowed: false, message: result.stderr || 'Blocked by hook' }
  }
  return { allowed: true }
}

// Migrated hooks (0t6) live in the TS dispatcher — run them via the package CLI
// instead of shelling out to a .sh file. Same JSON stdin protocol, same exit
// codes (0 = allow, 2 = block).
function runDispatchedHook(
  name: string,
  input: unknown,
): { allowed: boolean; message?: string } {
  const result = spawnSync('oisin-dev', ['hook', name], {
    input: JSON.stringify(input),
    encoding: 'utf8',
    timeout: 30_000,
  })

  if (result.status === 2) {
    return { allowed: false, message: result.stderr || 'Blocked by hook' }
  }
  return { allowed: true }
}

export default {
  name: 'dev-enforcer',
  async 'tool.execute.before'(event: ToolEvent): Promise<void> {
    const key = toolKey(event.tool)
    const toolInput = { tool_name: event.tool, tool_input: event.input }

    // Destructive bash commands
    if (isReadTool(key)) {
      const docs = runHook('docs-first.sh', toolInput)
      if (!docs.allowed) {
        throw new Error(docs.message)
      }
      return
    }

    if (isTodoTool(key)) {
      const block = runHook('block-todowrite.sh', toolInput)
      if (!block.allowed) {
        throw new Error(block.message)
      }
      return
    }

    if (isShellTool(key)) {
      const destructive = runHook('destructive-command-guard.sh', toolInput)
      if (!destructive.allowed) {
        throw new Error(destructive.message)
      }
      const coauthor = runDispatchedHook('block-coauthor', toolInput)
      if (!coauthor.allowed) {
        throw new Error(coauthor.message)
      }
      return
    }

    // Fabricated imports and anti-patterns on write/edit
    if (isWriteTool(key)) {
      const worktree = runHook('worktree-write-guard.sh', toolInput)
      if (!worktree.allowed) {
        throw new Error(worktree.message)
      }
      if (BEADS_ENABLED) {
        const claim = runHook('require-claim.sh', toolInput)
        if (!claim.allowed) {
          throw new Error(claim.message)
        }
        const swarm = runHook('require-swarm.sh', toolInput)
        if (!swarm.allowed) {
          throw new Error(swarm.message)
        }
      }
      if (HAS_TYPESCRIPT) {
        const style = runHook('ts-style-guard.sh', toolInput)
        if (!style.allowed) {
          throw new Error(style.message)
        }
        const imports = runHook('import-validator.sh', toolInput)
        if (!imports.allowed) {
          throw new Error(imports.message)
        }
      }
      const antipattern = runHook('ai-antipattern-guard.sh', toolInput)
      if (!antipattern.allowed) {
        throw new Error(antipattern.message)
      }
      return
    }

  },
}
`
}
