// dev-enforcer.ts — generated by @oisincoveney/dev
// OpenCode overlay. Shared policy lives in AGENTS.md; hook behavior delegates to .claude/hooks.

import { spawnSync } from 'node:child_process'
import { existsSync } from 'node:fs'
import { join } from 'node:path'

interface ToolEvent {
  tool: string
  input: Record<string, unknown>
}

const HOOKS_DIR = '.claude/hooks'
const HAS_TYPESCRIPT = true
const BEADS_ENABLED = true
const WORKTREE_POLICY = 'Agent implementation work, including /quick, must use Worktrunk worktrees under .agents/worktrees. Clones, temp scratch paths, and TMPDIR overrides are blocked.'
const STACK_POLICY = 'git-spice owns stack-aware branch, commit, restack, push, and PR operations. Direct git/gh commands for those operations are blocked.'

function toolKey(tool: string): string {
  return tool.toLowerCase().replace(/[^a-z0-9_]+/g, '_').replace(/^_+|_+$/g, '')
}

function runHook(name: string, input: unknown): { allowed: boolean; message?: string } {
  const path = join(HOOKS_DIR, name)
  if (!existsSync(path)) return { allowed: true }
  const result = spawnSync(path, [], {
    input: JSON.stringify(input),
    encoding: 'utf8',
    timeout: 30_000,
  })
  if (result.status === 2) return { allowed: false, message: result.stderr || 'Blocked by hook' }
  return { allowed: true }
}

function runDispatchedHook(name: string, input: unknown): { allowed: boolean; message?: string } {
  const result = spawnSync('oisin-dev', ['hook', name], {
    input: JSON.stringify(input),
    encoding: 'utf8',
    timeout: 30_000,
  })
  if (result.status === 2) return { allowed: false, message: result.stderr || 'Blocked by hook' }
  return { allowed: true }
}

export default {
  name: 'dev-enforcer',
  async 'tool.execute.before'(event: ToolEvent): Promise<void> {
    const key = toolKey(event.tool)
    const toolInput = { tool_name: event.tool, tool_input: event.input }

    if (key.includes('todo')) {
      const block = runHook('block-todowrite.sh', toolInput)
      if (!block.allowed) throw new Error(block.message)
      return
    }

    if (key.includes('bash') || key.includes('shell') || key.includes('exec')) {
      const destructive = runHook('destructive-command-guard.sh', toolInput)
      if (!destructive.allowed) throw new Error(destructive.message)
      void WORKTREE_POLICY
      const stack = runHook('git-spice-command-guard.sh', toolInput)
      if (!stack.allowed) throw new Error(stack.message)
      void STACK_POLICY
      const coauthor = runDispatchedHook('block-coauthor', toolInput)
      if (!coauthor.allowed) throw new Error(coauthor.message)
      return
    }

    if (key.includes('write') || key.includes('edit') || key.includes('patch')) {
      const worktree = runHook('worktree-write-guard.sh', toolInput)
      if (!worktree.allowed) throw new Error(worktree.message)
      void BEADS_ENABLED
      if (HAS_TYPESCRIPT) {
        const style = runHook('ts-style-guard.sh', toolInput)
        if (!style.allowed) throw new Error(style.message)
        const imports = runHook('import-validator.sh', toolInput)
        if (!imports.allowed) throw new Error(imports.message)
      }
      const antipattern = runHook('ai-antipattern-guard.sh', toolInput)
      if (!antipattern.allowed) throw new Error(antipattern.message)
    }
  },
}
