// dev-enforcer.ts — generated by @oisincoveney/dev
// Intercepts opencode tool.execute.before events and enforces the same rules
// as the Claude Code hooks by running the shared bash hooks.

import { spawnSync } from 'node:child_process'
import { existsSync } from 'node:fs'
import { join } from 'node:path'

interface ToolEvent {
  tool: string
  input: Record<string, unknown>
}

const HOOKS_DIR = '.claude/hooks'

function runHook(name: string, input: unknown): { allowed: boolean; message?: string } {
  const path = join(HOOKS_DIR, name)
  if (!existsSync(path)) return { allowed: true }

  const result = spawnSync(path, [], {
    input: JSON.stringify(input),
    encoding: 'utf8',
    timeout: 30_000,
  })

  if (result.status === 2) {
    return { allowed: false, message: result.stderr || 'Blocked by hook' }
  }
  return { allowed: true }
}

// Migrated hooks (0t6) live in the TS dispatcher — run them via the package CLI
// instead of shelling out to a .sh file. Same JSON stdin protocol, same exit
// codes (0 = allow, 2 = block).
function runDispatchedHook(
  name: string,
  input: unknown,
): { allowed: boolean; message?: string } {
  const result = spawnSync('oisin-dev', ['hook', name], {
    input: JSON.stringify(input),
    encoding: 'utf8',
    timeout: 30_000,
  })

  if (result.status === 2) {
    return { allowed: false, message: result.stderr || 'Blocked by hook' }
  }
  return { allowed: true }
}

export default {
  name: 'dev-enforcer',
  async 'tool.execute.before'(event: ToolEvent): Promise<void> {
    const toolInput = { tool_input: event.input }

    // Destructive bash commands
    if (event.tool === 'bash') {
      const destructive = runHook('destructive-command-guard.sh', toolInput)
      if (!destructive.allowed) {
        throw new Error(destructive.message)
      }
      const coauthor = runDispatchedHook('block-coauthor', toolInput)
      if (!coauthor.allowed) {
        throw new Error(coauthor.message)
      }
      return
    }

    // Fabricated imports and anti-patterns on write/edit
    if (['write', 'edit', 'multiedit', 'patch'].includes(event.tool)) {
      const imports = runHook('import-validator.sh', toolInput)
      if (!imports.allowed) {
        throw new Error(imports.message)
      }
      const antipattern = runHook('ai-antipattern-guard.sh', toolInput)
      if (!antipattern.allowed) {
        throw new Error(antipattern.message)
      }
      const style = runHook('ts-style-guard.sh', toolInput)
      if (!style.allowed) {
        throw new Error(style.message)
      }
      return
    }

    // Block todo writes
    if (event.tool === 'todowrite' || event.tool === 'todo_write') {
      const block = runHook('block-todowrite.sh', toolInput)
      if (!block.allowed) {
        throw new Error(block.message)
      }
    }
  },
}
