// dev-enforcer.ts — generated by @oisincoveney/dev
// Intercepts opencode lifecycle events and enforces the same rules
// as the Claude Code hooks via the shared TS dispatcher.

import { spawnSync } from 'node:child_process'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'

// ─── Hook runner ───────────────────────────────────────────────────────

interface HookResult {
  blocked: boolean
  message?: string
  context?: string
}

/** Run a hook via the TS dispatcher with fallback to shell scripts.
 *
 *  Strategy:
 *   1. oisin-dev hook <name>     (global install)
 *   2. npx oisin-dev hook <name> (on-demand, works without global)
 *   3. .claude/hooks/<name>.sh   (legacy shell script fallback)
 *
 *  All three fail → fail open (allow). A buggy hook never deadlocks the agent.
 */
function runHook(name: string, input: Record<string, unknown>): HookResult {
  const hookInput = JSON.stringify(input)

  // Attempt 1: global oisin-dev
  let result = spawnSync('oisin-dev', ['hook', name], {
    input: hookInput,
    encoding: 'utf8',
    timeout: 30_000,
  })
  if (!result.error) return interpretResult(result)

  // Attempt 2: npx (works without global install)
  result = spawnSync('npx', ['--yes', 'oisin-dev', 'hook', name], {
    input: hookInput,
    encoding: 'utf8',
    timeout: 60_000,
  })
  if (!result.error) return interpretResult(result)

  // Attempt 3: legacy shell script
  const scriptPath = join('.claude', 'hooks', name + '.sh')
  if (!existsSync(scriptPath)) return { blocked: false }
  result = spawnSync('bash', [scriptPath], {
    input: hookInput,
    encoding: 'utf8',
    timeout: 30_000,
  })
  if (!result.error) return interpretResult(result)

  // All failed → fail open
  return { blocked: false }
}

function interpretResult(
  result: ReturnType<typeof spawnSync>,
): HookResult {
  if (result.status === 2) {
    return { blocked: true, message: result.stderr?.trim() || 'Blocked by hook' }
  }

  if (result.stdout?.trim()) {
    try {
      const parsed = JSON.parse(result.stdout.trim())
      if (parsed.hookSpecificOutput?.additionalContext) {
        return { blocked: false, context: parsed.hookSpecificOutput.additionalContext }
      }
    } catch { /* not JSON, ignore */ }
  }

  return { blocked: false }
}

// ─── Session state ─────────────────────────────────────────────────────

const bashCommandsThisSession: string[] = []

// ─── Plugin ────────────────────────────────────────────────────────────

export default {
  name: 'dev-enforcer',

  // ── SessionStart ─────────────────────────────────────────────────────
  // Inject static context once per chat (caveman mode, project config, deps, baseline)
  async 'experimental.chat.system.transform'(_input, output) {
    const cwd = process.cwd()

    const bootstrap = runHook('context-bootstrap', { cwd })
    if (bootstrap.context) output.system.push(bootstrap.context)

    const baseline = runHook('baseline-pin', { cwd })
    if (baseline.context) output.system.push(baseline.context)
  },

  // ── UserPromptSubmit ─────────────────────────────────────────────────
  // Inject per-turn context (branch, bd state) into every user message
  async 'chat.message'(_input, output) {
    const cwd = process.cwd()

    const branch = runHook('context-injector', { cwd })
    if (branch.context) {
      if (typeof output.message.content === 'string') {
        output.message.content += '\n' + branch.context
      } else if (Array.isArray(output.message.content)) {
        output.message.content.push({ type: 'text', text: branch.context })
      }
    }

    const bd = runHook('bd-context-inject', { cwd })
    if (bd.context) {
      if (typeof output.message.content === 'string') {
        output.message.content += '\n' + bd.context
      } else if (Array.isArray(output.message.content)) {
        output.message.content.push({ type: 'text', text: bd.context })
      }
    }
  },

  // ── PreToolUse ───────────────────────────────────────────────────────
  // Guard before tool execution — throw to block, otherwise allow
  async 'tool.execute.before'(input, output) {
    const cwd = process.cwd()

    // All tools: audit log
    runHook('audit-log', { cwd, tool_name: input.tool, tool_input: output.args })

    // Bash: destructive commands, co-author, bd protection, plan approval
    if (input.tool === 'bash') {
      const cmd = output.args?.command ?? ''
      runHook('destructive-command-guard', { cwd, tool_input: { command: cmd } })
      runHook('block-coauthor', { cwd, tool_input: { command: cmd } })
      runHook('bd-remember-protect', { cwd, tool_input: { command: cmd } })
      runHook('plan-approval-guard', { cwd, tool_input: { command: cmd } })
      runHook('bd-create-gate', { cwd, tool_input: { command: cmd } })
      return
    }

    // Write/Edit: anti-patterns, claim/swarm gating, worktree, TS style, imports
    if (['write', 'edit', 'multiedit', 'patch'].includes(input.tool)) {
      const filePath = output.args?.file_path ?? output.args?.filePath ?? ''
      const content = output.args?.content ?? output.args?.new_string ?? output.args?.newString ?? ''
      const guardInput = { cwd, tool_input: { file_path: filePath, content, new_string: content } }

      runHook('ai-antipattern-guard', guardInput)
      runHook('require-claim', guardInput)
      runHook('require-swarm', guardInput)
      runHook('worktree-write-guard', guardInput)
      runHook('ts-style-guard', guardInput)
      runHook('import-validator', guardInput)
      return
    }

    // TodoWrite: blocked entirely (use bd instead)
    if (['todowrite', 'todo_write'].includes(input.tool)) {
      const result = runHook('block-todowrite', { cwd, tool_input: output.args })
      if (result.blocked) throw new Error(result.message!)
      return
    }

    // Read/Glob: docs-first redirect
    if (['read', 'glob'].includes(input.tool)) {
      runHook('docs-first', { cwd, tool_input: output.args })
      return
    }
  },

  // ── PostToolUse ──────────────────────────────────────────────────────
  // Check after write/edit (typecheck + lint), track bash commands
  async 'tool.execute.after'(input, output) {
    if (['write', 'edit'].includes(input.tool)) {
      const cwd = process.cwd()
      const filePath = input.args?.file_path ?? input.args?.filePath ?? ''

      const result = runHook('post-edit-check', { cwd, tool_input: { file_path: filePath } })
      if (result.blocked) throw new Error(result.message!)

      runHook('ai-antipattern-guard', { cwd, tool_input: input.args })
    }

    // Track bash commands for stop-verification proof-of-work
    if (input.tool === 'bash') {
      const cmd = input.args?.command ?? ''
      if (cmd) bashCommandsThisSession.push(cmd)
    }
  },

  // ── Stop ─────────────────────────────────────────────────────────────
  // Verification before session ends — block completion claims without proof
  async 'experimental.text.complete'(_input, output) {
    const cwd = process.cwd()
    const text = output.text

    // Only gate on completion claims, not on every stop
    if (!claimsCompletion(text)) return

    // Proof of work: test command must have been run
    const testCmd = getTestCommand(cwd)
    if (testCmd && !bashCommandsThisSession.some((c) => c.includes(testCmd))) {
      throw new Error(
        'Proof of work required.\n\n' +
          'You claimed completion but \'' + testCmd + '\' was not run this session.\n\n' +
          'Run: ' + testCmd + '\n' +
          'Show the output. Then report done.',
      )
    }

    // Baseline comparison — run tests and check for regressions
    runHook('baseline-compare', { cwd, hook_event_name: 'Stop' })

    // Banned words check (no follow-up questions)
    const banned = runHook('banned-words-guard', { cwd, transcript_text: text })
    if (banned.blocked) throw new Error(banned.message!)

    // Citation check
    const citations = runHook('citation-check', { cwd, transcript_text: text })
    if (citations.blocked) throw new Error(citations.message!)

    // Anti-pattern check on final output
    runHook('ai-antipattern-guard', { cwd, tool_input: { content: text } })

    // Worktree lifecycle guard — blocks stop if worker hasn't finished
    const worktree = runHook('worktree-stop-guard', { cwd })
    if (worktree.blocked) throw new Error(worktree.message!)

    // Swarm digest — appends active swarm summary (never blocks)
    const swarm = runHook('swarm-digest', { cwd })
    if (swarm.context) output.text += '\n' + swarm.context
  },

  // ── PreCompact ───────────────────────────────────────────────────────
  // Prime context before session compaction
  async 'experimental.session.compacting'(_input, output) {
    const cwd = process.cwd()
    const result = runHook('pre-compact-prime', { cwd })
    if (result.context) output.context.push(result.context)
  },
}

// ─── Helpers ───────────────────────────────────────────────────────────

/** Detects completion-claim language in the final assistant message.
 *  Conservative patterns — must look like a terminal completion statement. */
function claimsCompletion(text: string): boolean {
  return /this\s+(is\s+)?(now\s+)?(done|works?|working|complete|finished|ready)|should work( now)?\.?\s*$|all tests?\s+(pass(es)?|are\s+(green|passing))|task\s+(is\s+|now\s+)?complete|implementation\s+(is\s+|now\s+)?complete|everything\s+(is\s+|now\s+)?working|the\s+(changes?|fix|refactor)\s+(is\s+|are\s+|now\s+)?(done|complete|working)/i.test(text)
}

/** Reads the configured test command from .dev.config.json. */
function getTestCommand(cwd: string): string | null {
  const configPath = join(cwd, '.dev.config.json')
  if (!existsSync(configPath)) return null
  try {
    const config = JSON.parse(readFileSync(configPath, 'utf8')) as {
      commands?: { test?: string }
    }
    return config.commands?.test ?? null
  } catch {
    return null
  }
}
